---
#
# This credentials file is not encrypted for educational
# and demonstration purposes. It is highly recommended to
# encrypt this file with Ansible Vault or other encryption
# mechanism to protect your secrets!
#

# REST APIs
ise_username: admin
ise_password: C1sco12345
ise_verify: False

# Active Directory
ad_admin_username: administrator
ad_admin_password: C1sco12345

# Network Devices
radius_secret: C1sco12345
snmp_secret: C1sco12345
tacacs_secret: C1sco12345

# Repository
repository_username: ise
repository_password: C1sco12345

# Backup and Restore
backup_encryption_key: C1sco12345

...