---
# - name: Create Network Devices Play
#   hosts: ise_deployment
#   vars:
#   vars_files:
#     - credentials.yaml
#   gather_facts: no
#   tasks:

  - name: Network Device - WLC
    vars:
      device_name: TFD-WLC
      description: Cisco vWLC
      ipv4: 198.19.11.10
      profile_name: Cisco
      network_device_groups:
        - Device Type#All Device Types#Wireless#WLC
        - Location#All Locations#AMER#SJC
    cisco.ise.network_device:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: present
      name: "{{ device_name }}"
      description: "{{ device_name }}"
      profileName: "{{ profile_name | default(Cisco) }}"
      NetworkDeviceIPList:
      - ipaddress: "{{ ipv4 }}"
        mask: 32
      NetworkDeviceGroupList: "{{ network_device_groups }}"
      authenticationSettings:
        networkProtocol: RADIUS
        radiusSharedSecret: "{{ radius_secret }}"
        enableKeyWrap: False
        dtlsRequired: False
        enableMultiSecret: string
      tacacsSettings:
        sharedSecret: "{{ tacacs_secret }}"
        connectModeOptions: "OFF"
        previousSharedSecret:
        previousSharedSecretExpiry: 0
      snmpsettings:
        version: TWO_C
        roCommunity: "{{ snmp_secret }}"
        authPassowrd: string
        privacyPassowrd: string
        pollingInterval: 28800
        linkTrapQuery: true
        macTrapQuery: true
        originatingPolicyServicesNode: Auto
      dtlsDnsName: "{{ device_name }}"
      coaPort: 0
    register: result


  - name: Network Device - TFD-MR46-1
    vars:
      device_name: TFD-MR46-1
      description: Cisco Meraki MR46
      # ipv4: 172.112.212.4
      ipv4: 10.80.60.151
      profile_name: Cisco
      network_device_groups:
      - Device Type#All Device Types#Wireless#MR46
      - Location#All Locations#AMER#HBC
    cisco.ise.network_device:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: present
      name: "{{ device_name }}"
      description: "{{ device_name }}"
      profileName: "{{ profile_name | default(Cisco) }}"
      NetworkDeviceIPList:
      - ipaddress: "{{ ipv4 }}"
        mask: 32
      NetworkDeviceGroupList: "{{ network_device_groups }}"
      authenticationSettings:
        networkProtocol: RADIUS
        radiusSharedSecret: "{{ radius_secret }}"
        enableKeyWrap: False
        dtlsRequired: False
        enableMultiSecret: string
      tacacsSettings:
        sharedSecret: "{{ tacacs_secret }}"
        connectModeOptions: "OFF"
        previousSharedSecret:
        previousSharedSecretExpiry: 0
      snmpsettings:
        version: TWO_C
        roCommunity: "{{ snmp_secret }}"
        authPassowrd: string
        privacyPassowrd: string
        pollingInterval: 28800
        linkTrapQuery: true
        macTrapQuery: true
        originatingPolicyServicesNode: Auto
      dtlsDnsName: "{{ device_name }}"
      coaPort: 0
    register: result


  - name: Network Device - TFD-3560CX-1
    vars:
      device_name: TFD-3560CX-1
      description: Cisco 3560CX
      # ipv4: 172.112.212.4
      ipv4: 10.80.60.152
      profile_name: Cisco
      network_device_groups:
      - Device Type#All Device Types#Switches#3560CX
      - Location#All Locations#AMER#HBC
    cisco.ise.network_device:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: present
      name: "{{ device_name }}"
      description: "{{ device_name }}"
      profileName: "{{ profile_name | default(Cisco) }}"
      NetworkDeviceIPList:
      - ipaddress: "{{ ipv4 }}"
        mask: 32
      NetworkDeviceGroupList: "{{ network_device_groups }}"
      authenticationSettings:
        networkProtocol: RADIUS
        radiusSharedSecret: "{{ radius_secret }}"
        enableKeyWrap: False
        dtlsRequired: False
        enableMultiSecret: string
      tacacsSettings:
        sharedSecret: "{{ tacacs_secret }}"
        connectModeOptions: "OFF"
        previousSharedSecret:
        previousSharedSecretExpiry: 0
      snmpsettings:
        version: TWO_C
        roCommunity: "{{ snmp_secret }}"
        authPassowrd: string
        privacyPassowrd: string
        pollingInterval: 28800
        linkTrapQuery: true
        macTrapQuery: true
        originatingPolicyServicesNode: Auto
      dtlsDnsName: "{{ device_name }}"
      coaPort: 0
    register: result


  - name: Network Device - TFD-MS120-1
    vars:
      device_name: TFD-MS120-1
      description: Cisco 3560CX
      # ipv4: 172.112.212.4
      ipv4: 10.80.60.153
      profile_name: Cisco
      network_device_groups:
      - Device Type#All Device Types#Switches#MS120
      - Location#All Locations#AMER#HBC
    cisco.ise.network_device:
      ise_hostname: "{{ inventory_hostname }}"
      ise_username: "{{ ise_username }}"
      ise_password: "{{ ise_password }}"
      ise_verify: "{{ ise_verify }}"
      state: present
      name: "{{ device_name }}"
      description: "{{ device_name }}"
      profileName: "{{ profile_name | default(Cisco) }}"
      NetworkDeviceIPList:
      - ipaddress: "{{ ipv4 }}"
        mask: 32
      NetworkDeviceGroupList: "{{ network_device_groups }}"
      authenticationSettings:
        networkProtocol: RADIUS
        radiusSharedSecret: "{{ radius_secret }}"
        enableKeyWrap: False
        dtlsRequired: False
        enableMultiSecret: string
      tacacsSettings:
        sharedSecret: "{{ tacacs_secret }}"
        connectModeOptions: "OFF"
        previousSharedSecret:
        previousSharedSecretExpiry: 0
      snmpsettings:
        version: TWO_C
        roCommunity: "{{ snmp_secret }}"
        authPassowrd: string
        privacyPassowrd: string
        pollingInterval: 28800
        linkTrapQuery: true
        macTrapQuery: true
        originatingPolicyServicesNode: Auto
      dtlsDnsName: "{{ device_name }}"
      coaPort: 0
    register: result


  # - name: "Get Network Device by Name: {{ device_name }}"
  #   cisco.ise.network_device_info:
  #     ise_hostname: "{{ inventory_hostname }}"
  #     ise_username: "{{ ise_username }}"
  #     ise_password: "{{ ise_password }}"
  #     ise_verify: "{{ ise_verify }}"
  #     name: "{{ device_name }}"
  #   register: result


  # - name: Result
  #   ansible.builtin.debug: var=result


  # - name: Remove link attribute from all resources in loop
  #   ansible.builtin.set_fact:
  #     resources: '{{ resources + [ item.ise_response | dict2items | rejectattr("key", "equalto", "link") | list | items2dict ] }}'
  #   loop: "{{ result.results }}"
  #   vars: 
  #     resources: []
  #   when: resources and resources != []


  # - name: "Dump Network Device(s): {{ device_name }}"
  #   ansible.builtin.shell: 
  #     "echo '{{ result.ise_response | to_nice_yaml(indent=2) }}' > /dev/tty"
  #   delegate_to: localhost
  #   changed_when: false

...